version: "3"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
        - db_data:/var/lib/mysql
volumes:
  db_data:


